[build]
  builder = "nixpacks"
  watchPatterns = ["backend/**"]

[deploy]
  startCommand = "cd backend && npm start"
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 10
  healthcheckPath = "/health"
  healthcheckTimeout = 30

[nixpacks]
  nodeVersion = "18"
  installCmd = "cd backend && npm install"
  buildCmd = "cd backend && npm run build"
