[build]
  builder = "nixpacks"

[deploy]
  startCommand = "npm start"
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 10
  healthcheckPath = "/health"
  healthcheckTimeout = 30

[nixpacks]
  nodeVersion = "18"
